ALTER TYPE service_status ADD VALUE IF NOT EXISTS 'COMMISSION_PAID';
ALTER TYPE service_status RENAME VALUE 'REGISTERED' TO 'COMMISSION_PENDING';
ALTER TABLE performed_service
ALTER COLUMN status SET DEFAULT 'COMMISSION_PENDING';