CREATE TABLE service_type (
    id UUID PRIMARY KEY UNIQUE NOT NULL,
    name VARCHAR UNIQUE NOT NULL,
    base_price DECIMAL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);